apiVersion: v1
data:
  password: XlR6YUojVzRIUHJhIUtjK1ZxczduQFVncSFRaFhrNyNeVHphSiNXNEhQcmEhS2MrVnFzN25AVWdxIVFoWGs3Iy0tRFIqMnFSK1R6ei0tRFIqMnFSK1R6eg==
  user: NlJEZ25xRFg0YWNSQ0xWMnBZNG1kZA==
kind: Secret
metadata:
  labels:
    app: grafana
    chart: grafana-0.0.31
    heritage: Tiller
    io.cattle.field/appId: grafana
    release: grafana
  name: grafana-grafana
  namespace: grafana
type: Opaque
